### ISSUE TITLE
Failure of apply dff step

### ISSUE THREAD

**Issue by rvweeren** [lmorabit/long_baseline_pipeline#47]
It seems to fail at the killMS2H5parm.py step. Not sure why though....

2019-10-24 07:22:54 INFO    genericpipeline: Beginning step createmap_ddf
2019-10-24 07:22:54 INFO    genericpipeline: Beginning step ddf_solutions
2019-10-24 07:22:54 INFO    genericpipeline: Beginning step ddf_h5parms
2019-10-24 07:22:54 INFO    genericpipeline: Beginning step convert_to_h5
2019-10-24 07:22:54 INFO    genericpipeline: Running task: executable_args
2019-10-24 07:22:54 INFO    genericpipeline.executable_args: recipe executable_args started
2019-10-24 07:22:54 INFO    genericpipeline.executable_args: Starting /opt/lofar/losoto//bin/killMS2H5parm.py run
Reading configuration file: pipeline.cfg
Reading task definition file(s): /opt/lofar/lofar/share/pipeline/tasks.cfg
2019-10-24 07:22:54 DEBUG   genericpipeline.executable_args: Pipeline start time: 2019-10-22T12:50:19
2019-10-24 07:22:54 ERROR   genericpipeline.executable_args: Exception caught: list index out of range
Traceback (most recent call last):
  File "/opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/cuisine/WSRTrecipe.py", line 132, in run
    status = self.go()
  File "/opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/recipes/master/executable_args.py", line 357, in go
    arglist_copy[ind] = arglist_copy[ind].replace(name, value[i])
IndexError: list index out of range
2019-10-24 07:22:54 WARNING genericpipeline: executable_args reports failure (using executable_args recipe)
2019-10-24 07:22:54 ERROR   genericpipeline: *******************************************
2019-10-24 07:22:54 ERROR   genericpipeline: Failed pipeline run: LB-Delay-Calibration
2019-10-24 07:22:54 ERROR   genericpipeline: Detailed exception information:
2019-10-24 07:22:54 ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2019-10-24 07:22:54 ERROR   genericpipeline: executable_args failed
2019-10-24 07:22:54 ERROR   genericpipeline: *******************************************
2019-10-24 07:22:54 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
2019-10-24 07:22:55 WARNING genericpipeline: recipe genericpipeline completed with errors
Results:

**Comment by lmorabit** [comment]
Generally these 'list index out of range' errors come from a mapfile error.  The two mapfiles that go in to this step are from the ddf_solutions and ddf_h5parms steps -- it's probably the first of these steps since the latter writes a mapfile for the output h5 files. Can you check if ddf_solutions is pointed to the right directory in your parset?  i.e. check `! ddf_soldir = ` on line 46 and make sure it's pointing to the right place (the ddf-pipeline SOLSDIR) and that L*pre-cal.ms exist in that directory.

**Comment by rvweeren** [comment]
@lmorabit , yes I thought that was the problem but I double checked that ddf_soldir is correct

ddf_soldir			= /net/rijn/data2/rvweeren/A2256_LB/DR2/SOLSDIR

ls /net/rijn/data2/rvweeren/A2256_LB/DR2/SOLSDIR

ls /net/rijn/data2/rvweeren/A2256_LB/DR2/SOLSDIR  
L719874_SB001_uv_12DF5BEDAt_121MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_123MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_125MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_127MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_129MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_130MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_132MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_134MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_136MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_138MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_140MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_142MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_144MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_146MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_148MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_150MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_152MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_154MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_156MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_158MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_160MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_162MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_164MHz.pre-cal.ms
L719874_SB001_uv_12DF5BEDAt_166MHz.pre-cal.ms

**Comment by lmorabit** [comment]
and do the killMS.DIS2_full.sols.npz exist in the L*pre-cal.ms directories?

**Comment by rvweeren** [comment]
I noticed that the international baseline pipeline created 

L719874_SB001_uv_12DF5BED9t_168MHz.msdpppconcat

but there is no corresponding killMS.DIS2_full.sols.npz for that from DR2, because that block is more than 50% flagged so it's not processed in the DDF-pipeline. Could that be the issue? On the other hand looking at the code it should not fail on that...

**Comment by rvweeren** [comment]
Yes, killMS.DIS2_full.sols.npz exist

ls /net/rijn/data2/rvweeren/A2256_LB/DR2/SOLSDIR/*/killMS.DIS2_full.sols.npz
/net/rijn/data2/rvweeren/A2256_LB/DR2/SOLSDIR/L719874_SB001_uv_12DF5BEDAt_121MHz.pre-cal.ms/killMS.DIS2_full.sols.npz
/net/rijn/data2/rvweeren/A2256_LB/DR2/SOLSDIR/L719874_SB001_uv_12DF5BEDAt_123MHz.pre-cal.ms/killMS.DIS2_full.sols.npz
/net/rijn/data2/rvweeren/A2256_LB/DR2/SOLSDIR/L719874_SB001_uv_12DF5BEDAt_125MHz.pre-cal.ms/killMS.DIS2_full.sols.npz
etc.

**Comment by lmorabit** [comment]
Ah yes, I am pretty sure that will be the issue -- it will be a mis-match
in the mapfile in and mapfile out.  This has been a problem before, and we
need some sort of check at the beginning so we don't process those
subbands.  I'll add it to the list for the busy week.

**Comment by rvweeren** [comment]
@lmorabit, yes you are right,  if I create a "fake" L719874_SB001_uv_12DF5BEDAt_168MHz.pre-cal.ms in SOLSDIR the pipeline continues, so it is indeed a mapping file mismatch.

(I just did a cp -r SOLSDIR/L719874_SB001_uv_12DF5BEDAt_166MHz.pre-cal.ms to  SOLSDIR/L719874_SB001_uv_12DF5BEDAt_168MHz.pre-cal.ms and then I will ignore L719874_SB001_uv_12DF5BED9t_168MHz.msdpppconcat in the end)

**Comment by lmorabit** [comment]
Okay, glad it's working.  Annoyingly it's not an issue with the actual
code, it's a generic pipeline issue.  We have to add a step at the
beginning of the parset to check the subband coverage and only process
those needed so you don't end up with the unnecessary *dpppconcat file.

**Comment by rvweeren** [comment]
I managed to get beyond the point but then get a DPPP error

_std exception detected: Frequency 167094421.386719 not found in sol001/phase000_

this error makes sense since the H5 file was copied from the 166 MHz block and does not match the freq of the 168 MHz block, so my temporary hack is not working. For now I will simply delete all input target SB that go into the 168 MHz block, so the 168 MHz block is never made in the first place.

**Comment by lmorabit** [comment]
That does make sense, and the fix I hope to implement (on my to do for next
week) should take care of that.  Thanks for the updates.

**Comment by lmorabit** [comment]
Should be fixed with commit 31fd427bb0878604ad22dd4edf6bed288fb69ce0 .
