### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cyriltasse** [lmorabit/long_baseline_pipeline#95]
It gets a bit further after the change I did yesterday, but has a syntax error, not sure why... Maybe an argument with wrong formatting has been passed to `facetselfcal.py`

```
2023-04-21 22:56:38 WARNING genericpipeline.executable_args: /opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
2023-04-21 22:56:39 WARNING genericpipeline.executable_args: Debug: registered context Global=0
2023-04-21 22:56:46 WARNING genericpipeline.executable_args: Traceback (most recent call last):
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 6463, in <module>
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:     main()
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 6046, in main
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:     lineval = arg_as_list(lineval)
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 5726, in arg_as_list
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:     v = ast.literal_eval(s)
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:   File "/usr/lib64/python2.7/ast.py", line 49, in literal_eval
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:     node_or_string = parse(node_or_string, mode='eval')
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:   File "/usr/lib64/python2.7/ast.py", line 37, in parse
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:     return compile(source, filename, mode, PyCF_ONLY_AST)
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:   File "<unknown>", line 1
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:     [/data/levangelista/LOFAR_VLBI_PIPELINE/RUN_DIR/Split-Directions/../Delay-Calibration/delay_solve/merged_addCS_selfcalcyle009_linearfulljones_ILTJ120449.84+392947.8_L402151_SB244_uv.dppp_1273342BDt_121MHz_1273342CCt_141MHz.msdpppconcat.copy.phaseup.h5]
2023-04-21 22:56:46 WARNING genericpipeline.executable_args:      ^
2023-04-21 22:56:46 WARNING genericpipeline.executable_args: SyntaxError: invalid syntax
2023-04-21 22:56:47 WARNING genericpipeline.executable_args: 

```

**Comment by cyriltasse** [comment]
it looks like there are `""` missing...

**Comment by cyriltasse** [comment]
I've done a really dirty hack in `facetselfcal.py` just to see if the missing quotes are the cause of the trouble. It's a little obscure how to change it to the call on top.

**Comment by cyriltasse** [comment]
Ok - it gets further with my dirty fix of the problem above, but then a different issue i believe:

```
Reading task definition file(s): /opt/lofar/lofar/share/pipeline/tasks.cfg
2023-04-22 12:42:28 WARNING genericpipeline.executable_args: /opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
2023-04-22 12:42:28 WARNING genericpipeline.executable_args: Debug: registered context Global=0
2023-04-22 12:42:35 WARNING genericpipeline.executable_args: Traceback (most recent call last):
2023-04-22 12:42:35 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 6474, in <module>
2023-04-22 12:42:35 WARNING genericpipeline.executable_args:     main()
2023-04-22 12:42:35 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 6061, in main
2023-04-22 12:42:35 WARNING genericpipeline.executable_args:     raise KeyError('Encountered invalid option {:s} in config file {:s}.'.format(arg, os.path.abspath('facetselfcal_config.txt')))
2023-04-22 12:42:35 WARNING genericpipeline.executable_args: KeyError: 'Encountered invalid option preapplyH5-list in config file /data/levangelista/LOFAR_VLBI_PIPELINE/RUN_DIR/Split-Directions/delay_solve/facetselfcal_config.txt.'
```

**Comment by cyriltasse** [comment]
I'm trying with changing `preapplyH5-list` to `preapplyH5_list`, I saw this is what's used in `facetselfcal.py`, it's a bit weird though what's in the options is `preapplyH5-list` (as with other parameters). @jwpetley did you test running your changes to `Split-Directions.parset`?

**Comment by cyriltasse** [comment]
I've also dropped comments on the commit https://github.com/lmorabit/lofar-vlbi/commit/0414cf5c3fcd34302bc685181beae21c7bf041bd

**Comment by tikk3r** [comment]
In the config file dashes should indeed be converted to underscores, so things like your example that would be  `--preapplyH5-list` on the command line should be `preapplyH5_list` in the config file (reason being that argparse converts dashes to underscores).

**Comment by cyriltasse** [comment]
Hey - i think it's doing something interesting ! So exciting!

![image](https://user-images.githubusercontent.com/6523227/233811818-a5737a2e-d67d-4c02-a84f-b8cee0382398.png)

Thanks for all the amazing work

**Comment by cyriltasse** [comment]
Ok - next error is `ERROR: Only type in [amplitude, phase] allowed.`:

```
Reading configuration file: pipeline.cfg
Reading task definition file(s): /opt/lofar/lofar/share/pipeline/tasks.cfg
2023-04-22 23:05:40 WARNING genericpipeline.executable_args: /opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
2023-04-22 23:05:40 WARNING genericpipeline.executable_args: Debug: registered context Global=0
2023-04-22 23:05:43 WARNING genericpipeline.executable_args: 
Reading configuration file: pipeline.cfg
Reading task definition file(s): /opt/lofar/lofar/share/pipeline/tasks.cfg
2023-04-22 23:05:44 WARNING genericpipeline.executable_args: /opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
2023-04-22 23:05:44 WARNING genericpipeline.executable_args: Debug: registered context Global=0
2023-04-22 23:08:01 WARNING genericpipeline.executable_args: 
Reading configuration file: pipeline.cfg
Reading task definition file(s): /opt/lofar/lofar/share/pipeline/tasks.cfg
2023-04-22 23:08:02 WARNING genericpipeline.executable_args: /opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
2023-04-22 23:08:02 WARNING genericpipeline.executable_args: Debug: registered context Global=0
2023-04-22 23:24:07 WARNING genericpipeline.executable_args: Warning: The input contains the deprecated ddecal.usemodelcolumn setting, possibly combined with the deprecated msin.modelcolumn setting. Please use ddecal.modeldatacolumns instead.
2023-04-22 23:46:26 WARNING genericpipeline.executable_args: Closing remaining open files:tec0_selfcalcyle000_ILTJ120752.09+385559.1_L402151_SB244_uv.dppp_1273342BDt_121MHz_1273342CCt_141MHz.msdpppconcat.copy.h5...done
2023-04-22 23:48:48 WARNING genericpipeline.executable_args: ERROR: Only type in [amplitude, phase] allowed.
2023-04-22 23:48:48 WARNING genericpipeline.executable_args: Closing remaining open files:tec0_selfcalcyle000_ILTJ120752.09+385559.1_L402151_SB244_uv.dppp_1273342BDt_121MHz_1273342CCt_141MHz.msdpppconcat.copy.h5...done
2023-04-22 23:48:49 WARNING genericpipeline.executable_args: 
Results:
```

it seems to be thrown by https://github.com/jurjen93/lofar_helpers/blob/e83db286d7edc848238cf887dcff1abb5c429486/h5_merger.py#L956 or just bellow this line. I've looked a bit but I don't see where the problem is...

**Comment by tikk3r** [comment]
Hmm, not sure. Maybe one for @jurjen93?

**Comment by cyriltasse** [comment]
I'm rerunning, I'll see what's passed to `h5_merger.py`

**Comment by jurjen93** [comment]
I guess the h5 files contains a table that my merger script hasnt been merging before, which is why it returns this error.
I see it is crashing on the part where it is modifying the polarization axis, which is done when not all input h5 files have the same number of polarizations (None, 1, 2 or 4). For phases, tec, and amplitudes it needs to do this differently, which why there is this extra check.
So, if you could give me the h5 file and the command, I can reproduce and check what it is trying to do and update the script if necessary.

**Comment by rvweeren** [comment]
Strange, this looks like some of the recent errors we had related to tec-merging which were support to be fixed. But maybe not @jurjen93 ?

**Comment by jurjen93** [comment]
Not sure, it looks like something else. This is a build-in check that crashes if the 'wrong input' (or something I haven't come across yet in my tests) is given in this function (haven't seen a merge ending up here).

**Comment by cyriltasse** [comment]
Ok I've had to rerun everything from start (the pipeline is realy hard to debug), and I've finally managed to have more information on the crash. To see what was given I've changed https://github.com/jurjen93/lofar_helpers/blob/c272a0ae6be4d2bb7e0391dc46cc966b306e2b04/h5_merger.py#L956 to

`sys.exit('ERROR: Only type in [amplitude, phase] allowed [1- %s requested].'%str(type))`

and the message being displayed is

`ERROR: Only type in [amplitude, phase] allowed [1- error requested]`

so somehow the string "error" is given is argument. I'll keep staring at the code, but if you have any obvious idea don't hesitate to share.

Also on a seperate issue, I've needed to change @rvweeren script `facetselfcal.py` to deal with `DP3` change in [this](https://github.com/lofar-astron/DP3/commit/e88baa301872f4f61c36e0636eb9291c75cb2b64) commit, otherwise it was crashing for me (see also https://github.com/lmorabit/lofar-vlbi/issues/92). Basically everywhere it was calibrating against a visibility column FOO change "modelcolumn=FOO" to "modeldatacolumns=[FOO]" and "usemodeldatacolumn" to "usemodelcolumn". The change is quite old already and I don't understand why others did not have to change it...

**Comment by rvweeren** [comment]
>Also on a seperate issue, I've needed to change @rvweeren script facetselfcal.py to deal with DP3 change in [this](https://github.com/lofar-astron/DP3/commit/e88baa301872f4f61c36e0636eb9291c75cb2b64) commit, otherwise it was crashing for me (see also https://github.com/lmorabit/lofar-vlbi/issues/92).

That's strange, we are using a much more recent DP3 version and have never encountered that issue. (DP3 only gives a warning about the old syntax). That said, updating facetselfcal to the more recent syntax is on the to-do list, will do that soon.

**Comment by jurjen93** [comment]
Hi @cyriltasse thanks for notifying the h5_merger crash.  
This part is reached when the polarization dimensions are not the same for all tables and the script needs to modify this to complete the merge correctly. Haven't seen the sys.exit for error tables before, so hadn't noticed this.
I have now updated the script, such that it is less conservative and also allows other table types to get through this part without exit.

**Comment by jurjen93** [comment]
If you could give me the h5 tables that it tries to merge (the names are given at the start of h5_merger), I can verify it if it now outputs the correct output

**Comment by cyriltasse** [comment]
Thanks @jurjen93 , launching again. Unfortunatly I've deleted my `Split-Directions` directory. I'll send you the h5 if it crashes again...

**Comment by cyriltasse** [comment]
Ok @jurjen93  it now crashes elsewhere in the script:

```
2023-05-04 13:52:32 WARNING genericpipeline.executable_args: Traceback (most recent call last):
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 6490, in <module>
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:     main()
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 6429, in main
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:     gapchanneldivision=args['gapchanneldivision'])
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 5091, in calibrateandapplycal
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:     convert_tec=True, merge_all_in_one=True, propagate_flags=True)
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_helpers/h5_merger.py", line 2529, in merge_h5
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:     merge.merge_tables('sol000', st)
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_helpers/h5_merger.py", line 1152, in merge_tables
2023-05-04 13:52:32 WARNING genericpipeline.executable_args:     self.error[i, idx, ...] += values[...]/self.errornum
2023-05-04 13:52:32 WARNING genericpipeline.executable_args: ValueError: non-broadcastable output operand with shape (67,115,899) doesn't match the broadcast shape (4,67,115,899)
2023-05-04 13:52:32 WARNING genericpipeline.executable_args: Closing remaining open files:tec0_selfcalcyle000_ILTJ120752.09+385559.1_L402151_SB244_uv.dppp_1273342BDt_121MHz_1273342CCt_141MHz.msdpppconcat.copy.h5...done

```

I've posted all the H5 parm I found in the `Split-direction` directory [here](https://share.obspm.fr/s/qTaTHreMgwnQZkR)

**Comment by jurjen93** [comment]
Hi @cyriltasse ,
h5_merger complained again about the type of merge with the error table due to the different polarization dimensions. This was luckily a simple change in my code to allow it to continue without crash and I could complete the merge between merged_addCS*.h5 and tec0*.h5 correctly myself now. (See latest version)

This problem (and this type of h5 merge) hasn't occurred before, so out of curiosity I wondered what you are currently trying with facetselfcal or if you have changed something in the script?

**Comment by cyriltasse** [comment]
Perfect thanks a lot for the quick fix! I'm rerunning. I'll let you know how this goes.

> This problem (and this type of h5 merge) hasn't occurred before, so out of curiosity I wondered what you are currently trying with facetselfcal or if you have changed something in the script?

Just following the instructions on the `lofar-vlbi` [site](https://lofar-vlbi.readthedocs.io/en/latest/running.html#running-the-lofar-vlbi-pipeline). I'm running `Split-Directions.parset` after running `Pre-Facet-Calibrator`, `Pre-Facet-Target`, and `Delay-Calibration` parsets. But I've understood this is coded/released, but unfortunatly not tested, and maybe I'm the only one doing it. So thanks for your help!

**Comment by cyriltasse** [comment]
Thanks @jurjen93 it passes the previous step. Unformtunatly it crashes elsewhere:

```
2023-05-07 14:13:30 WARNING genericpipeline.executable_args: Traceback (most recent call last):
2023-05-07 14:13:30 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 6490, in <module>
2023-05-07 14:13:30 WARNING genericpipeline.executable_args:     main()
2023-05-07 14:13:30 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 6429, in main
2023-05-07 14:13:30 WARNING genericpipeline.executable_args:     gapchanneldivision=args['gapchanneldivision'])
2023-05-07 14:13:30 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 5117, in calibrateandapplycal
2023-05-07 14:13:30 WARNING genericpipeline.executable_args:     medamp=medianamp(parmdbmergename), \
2023-05-07 14:13:30 WARNING genericpipeline.executable_args:   File "/data/levangelista/DEV_VLBI/lofar_facet_selfcal/facetselfcal.py", line 4664, in medianamp
2023-05-07 14:13:30 WARNING genericpipeline.executable_args:     medamps_cross = 0.5*(10**(np.nanmedian(np.log10(amps_xy[idx_xy]))) + 10**(np.nanmedian(np.log10(amps_yx[idx_yx]))))
2023-05-07 14:13:30 WARNING genericpipeline.executable_args: FloatingPointError: divide by zero encountered in log10
```

I'm really about to give up, and the genericpipeline is super hard to debug. Should I? @lmorabit @jwpetley did anyone ran `Split-directions` (successfully/at all) step before? What do you advice me to do?

**Comment by cyriltasse** [comment]
I've fixed the FloatingPointError and now it seems to be running, it did already 6 images of the brightest source above... Crossing fingers...

**Comment by lmorabit** [comment]
Sorry for the delayed replies, I've been travelling.

Happy to hear the FloatingPointError is resolved!  It's been a bit of a challenge to get facetselfcal.py working well with the generic pipeline.  One suggestion we can make is to run split-directions just to generate the measurement sets that go into the self-cal step, and run facetselfcal.py outside of the pipeline.

The CWL version of the lofar-vlbi pipeline is almost ready to go, although it needs some final testing so it will be several weeks before it's ready.

**Comment by cyriltasse** [comment]
Hi - thanks @lmorabit @jurjen93  for your help!

The floating point error seemed to be the (almost) last. Now it doesn't crash anymore, but I see two issues:

1- It only self cal the brightest source - and stop there... I guess `Split-Directions` is supposed to image all sources in  `image_catalogue.csv` right (my source of interest was second this list)? Do you have any suggestion how I could image my source of interest? And all sources in `image_catalogue.csv`? Proably a change in `Split-Direction.parset`?

2- The selfcal cycle does weird sources to pop in and out:

![image](https://github.com/lmorabit/lofar-vlbi/assets/6523227/5263e700-7b6d-4e6b-a26a-d7d014d1fe72)

**Comment by jwpetley** [comment]
1. In theory it should do all of them but I'm not sure that it is completely working at the moment. The `image_catalogue.csv` does everything in LoTSS above a certain flux limit I think. The easiest way to image one source of interest is to make a new `image_catalogue.csv` with just one entry with the information for that source.
2. Not sure what the reason is for it but I have seen similar things in some of my selfcal runs. Others probably have a better ideas

**Comment by lmorabit** [comment]
Yes, it should do everything in the `image_catalogue.csv` file, to which you can add, subtract, or re-order sources to get it to image what you want.  The selfcal run in Split-Directions hasn't been tested yet for a large number of fields, and the settings are still under development.  It would be good if you could join our next LB telecon to discuss this source -- this is the kind of thing we talk about in the group to help with development of the pipeline!

@cyriltasse in the parsets directory, what's in the dppp_phaseup parset?

**Comment by vijaymahatma** [comment]
I too have had similar results in self-cal runs -- in my experience this usually happens for large angular size objects (few arcmin, phasing up the superterp), and when you are solving for the gains based on emission in the field that is mostly seen by the Dutch baselines only (and is undetected with the international baselines).

**Comment by tikk3r** [comment]
@cyriltasse what did you have to do to fix the `FloatingPointError`? We haven't really encountered it before, so it's interesting that it pops up now.

Regarding that point 2 about the selfcal cycles: yeah that looks odd and unstable. As a first check, if you haven't done so already, I would look at the quality of the delay calibration by inspecting the solution plots and images that facetselfcal.py should have made when running on the delay calibrator. The solution plots live in a folder named `plotlosoto<msname>`.  If that is already compromised then subsequent selfcal on sources of interest will also suffer.

From the images it looks like this is a large source? @vmahat 's point is a good one in that case. If it's a few arcmin or larger then you probably don't want to do the phaseup of the core, as the field of view of the phased-up core is small.
